- name: Add a new filter to a tenant
  aci_filter:
    host: "{{ inventory_hostname }}"
    username: "{{ username }}"
    password: "{{ password }}"
    filter: "{{ item['filter'] }}"
    description: Filter add by Ansible
    tenant: "{{ tenant }}"
    state: present
    validate_certs: False
  loop: "{{ filters }}"
  register: create_filters
  ignore_errors: true

- name: Ensure filters have filter entries
  aci_filter_entry:
    host: "{{ inventory_hostname }}"
    username: "{{ username }}"
    password: "{{ password }}"
    state: "present"
    validate_certs: False
    tenant: "{{ tenant }}"
    filter: "{{ item['filter'] }}"
    entry: "{{ item['entry'] }}"
    ether_type: "ip"
    ip_protocol: "tcp"
    dst_port_start: "{{ item['port'] }}"
    dst_port_end: "{{ item['port'] }}"
  loop: "{{ filters }}"
  when: create_filters is succeeded