# tenant to deploy
tenant:  "aci-demo-gen-cap_tenant"

# vrf to deploy
vrf:     "aci-demo-gen-cap_vrf"

# vars for bridge domain and subnet
bd:      "aci-demo-gen-cap_bd"
gateway: "10.1.220.1"
mask:    "24"
scope:   "public"

# vars for policies and contracts
filters:
  - { filter: "https" , entry: "https" , port: 443  }
  - { filter: "sql"   , entry: "sql"   , port: 1433 }

contracts:
  - { contract: "web" , subject: "https" }
  - { contract: "sql" , subject: "sql"   }

# vars for application module
ap: "aci-demo-gen-cap_ap"

# vars for define EPGs
epgs:
  - { epg: "web" , encap: "21" , contract_type: "both"     , provider: "web" , consumer: "sql" }
  - { epg: "sql" , encap: "22" , contract_type: "provider" , provider: "sql" }

# vars for defined EPGs contracts
epg_contracts:
  - { epg: "web" , contract: "web" , contract_type: "provider" }
  - { epg: "web" , contract: "sql" , contract_type: "consumer" }
  - { epg: "sql" , contract: "sql" , contract_type: "provider" }